version: "3"

services:
  app:
    image: aesirxio/bi-app:latest
    pull_policy: always
    environment:
      REACT_APP_BI_ENDPOINT_URL: ${REACT_APP_BI_ENDPOINT_URL}
      REACT_APP_DATA_STREAM: ${REACT_APP_DATA_STREAM}
      REACT_APP_DEFAULT_USER: ${REACT_APP_DEFAULT_USER}
      REACT_APP_DEFAULT_PASSWORD: ${REACT_APP_DEFAULT_PASSWORD}
    ports:
      - "${PORT-3000}:3000"
